# Generated by Django 5.0.3 on 2024-03-30 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_running_line', '0003_alter_runninglinerequest_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runninglinerequest',
            name='text',
            field=models.TextField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
    ]
