# Generated by Django 5.0.3 on 2024-03-30 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_running_line', '0005_alter_runninglinerequest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninglinerequest',
            name='bg_color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator('^#[1-9A-Fa-f]{6}$', message='Color must be in hex format.')]),
        ),
        migrations.AddField(
            model_name='runninglinerequest',
            name='duration',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='runninglinerequest',
            name='fontsize',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='runninglinerequest',
            name='fps',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='runninglinerequest',
            name='height',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1920)]),
        ),
        migrations.AddField(
            model_name='runninglinerequest',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[1-9A-Fa-f]{6}$', message='Color must be in hex format.')]),
        ),
        migrations.AddField(
            model_name='runninglinerequest',
            name='width',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1920)]),
        ),
    ]
